### ISSUE TITLE
Bug al no entrar

### ISSUE THREAD

**Issue by Gatomano** [karv/Art-of-Meow#9]
El bug se manifiesta cuando quieres entrar, pero nunca te deja entrar , en cambio nunca lo hace y te muestra el siguiente error: Unhandled Exception: System.TypeLoadException: Could not load type 'AoM.Program' from assembly 'Art_of_Meow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'AoM.Program' from assembly 'Art_of_Meow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by karv** [comment]
¿`mono --version` ya dice que es > 4.0?

**Comment by karv** [comment]
Ah, ¿qué versión de Ubuntu estás usando? Voy a revisar compatibilidad de `mono` para esa distro
